export const TOPICS = [
  "Animals",
  "Space Exploration",
  "Historical Events",
  "Weird Foods",
  "Science Mysteries",
  "Ancient Civilizations",
  "Human Body Quirks",
  "Ocean Secrets",
  "Technology Innovations",
  "Celebrity Trivia",
  "Weather Phenomena",
  "Mythical Creatures",
  "Sports Records",
  "Literary Oddities",
  "Art History Surprises",
  "Plant Superpowers",
  "Useless Inventions",
  "Language Oddities",
  "Crime Heists",
  "Disney Behind-the-Scenes",
  "Bizarre Festivals",
  "Fashion Fails",
  "Conspiracy Theories",
  "Video Game Easter Eggs",
  "Unsolved Mysteries",
];
